language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "pypy"
install:
  - pip install -U tox pip
script:
  - tox
after_sucess:
    coveralls
